# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1451988196);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1451988316);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1452066037);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1451988076);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1451987956);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1451988436);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 31);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "TH");
user_pref("browser.search.region", "TH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151210085006");
user_pref("browser.slowStartup.averageTime", 14729);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20151210085006");
user_pref("browser.startup.homepage_override.mstone", "43.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1451461364525");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1451375102648");
user_pref("datareporting.policy.firstRunTime", "1451374964520");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.firstPaint", 8621);
user_pref("datareporting.sessions.current.main", 1231);
user_pref("datareporting.sessions.current.sessionRestored", 8947);
user_pref("datareporting.sessions.current.startTime", "1452071546972");
user_pref("datareporting.sessions.current.totalTime", 34);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.2", "{\"s\":1451376455423,\"a\":187,\"t\":689094,\"c\":true,\"m\":1045,\"fp\":15671,\"sr\":14903}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1452065911623,\"a\":15,\"t\":377,\"c\":true,\"m\":1112,\"fp\":16658,\"sr\":16404}");
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"43.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"43.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:43.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1451988198);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20151223.01");
user_pref("extensions.lastAppVersion", "43.0");
user_pref("extensions.lastPlatformVersion", "43.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"43.0\",\"st\":1449744438000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"43.0\",\"st\":1451375007000,\"mt\":1449741438000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"43.0\",\"st\":1449744438000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20151210085006");
user_pref("gecko.mstone", "43.0");
user_pref("idle.lastDailyNotification", 1451987866);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1451988207);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20151210085006");
user_pref("media.gmp-manager.lastCheck", 1452065989);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1451987867);
user_pref("places.history.expiration.transient_current_max_pages", 103186);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1451987867);
user_pref("toolkit.startup.last_success", 1452071548);
user_pref("toolkit.telemetry.cachedClientID", "4ef80a16-904b-498a-89fc-eefa617a7bb7");
user_pref("toolkit.telemetry.previousBuildID", "20151210085006");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
